pnw: Add telephony-ext to boot jar path and PRODUCT_PACKAGES
 * Include the telephony-ext jar library in PRODUCT_PACKAGES
 * and in boot jar path.
 * The telephony-ext jar is needed for MSIM manual provisioning
 * and other telephony related functionalities to work.

 * This works with now added Manual provisioning support to the
 * Settings. Without (com.android.phone) crashes and throws
 * "NoClassDefFoundError" errors which is really bad and forces
 * the device to restart.

 * This works also on this way: https://github.com/LineageOS/android_packages_apps_Settings/commit/6f2efa2875c2f2858ef4de97945e82742510472a
 * But we build telephony-ext now anyways.

Signed-off-by: OrdenKrieger <OrdenKriegerEDR@googlemail.com>